/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package src.frames.tabs;
import java.awt.Color;
import java.awt.Font;
import java.time.LocalDate;
import java.time.Period;
import java.util.ArrayList;
import src.frames.Frame;
import src.models.*;
import src.frames.tabs.DashboardComponents.viewAppointment;
import src.util.database;
/**
 *
 * Dashboard Tab
 */
public class Dashboard extends javax.swing.JPanel {

    /**
     * Current user
     */
    private user user;

    /**
     * Create a new Frame to use the font function
     */
    private Frame Frame = new Frame();
    /**
     * Constructor to create new Dashboard Tab
     */
    public Dashboard() {
        initComponents();
        Frame.dispose();
        headerPanel.setRound(50);
        scrollPanel.getViewport().setBackground(new Color(248, 249, 254));
        scrollPanel.getVerticalScrollBar().setUnitIncrement(14);
    }
    
    /**
     * font function used to init the Componenets with a modern Font
     * @param size of the font
     * @return 
     */
    public Font fnt(float size){
        return Frame.fnt(size);
    }
    
    /**
     * load all appointments from the database into the appointmentsPanel
     * we cant init the values in the constructor because the netbeans gui builder doesent allow custom parameters
     * @param user
     */
    public void init(user user){
        this.user = user;
        if(user.getAppointments() == null){
            user.setAppointments(database.getAppointments(user));
        }
        lblName.setText(user.getFirstname()+" "+user.getLastname());
        lblAge.setText(Period.between(user.getDateofbirth(), LocalDate.now()).getYears()+" years old");
        if(user.getGender().equals("f")){
            icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/icons/icons8-circled-user-female-skin-type-4-48.png")));
        }
        appointmentsPanel.removeAll();
        appointmentsPanel.revalidate();
        appointmentsPanel.repaint();
        ArrayList<appointment> appointments = user.getAppointments();
        for(int i = 0; i < appointments.size();i++){
            viewAppointment panel = new viewAppointment(this,appointments.get(i),user);
            appointmentsPanel.add(panel);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new src.frames.components.background();
        icon = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblHeader = new javax.swing.JLabel();
        scrollPanel = new javax.swing.JScrollPane();
        appointmentsPanel = new src.frames.tabs.DashboardComponents.appointmentsPanel();

        setBackground(new java.awt.Color(248, 249, 254));

        headerPanel.setBackground(new java.awt.Color(15, 95, 83));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/icons/icons8-circled-user-male-skin-type-3-48.png"))); // NOI18N

        lblName.setFont(fnt(16f));
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Nabil Akir");

        lblAge.setFont(fnt(14f));
        lblAge.setForeground(new java.awt.Color(255, 255, 255));
        lblAge.setText("38 years old");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(icon)
                .addGap(36, 36, 36)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName)
                    .addComponent(lblAge))
                .addContainerGap(308, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addComponent(lblName)
                        .addGap(8, 8, 8)
                        .addComponent(lblAge)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        lblHeader.setFont(fnt(22f));
        lblHeader.setText("Your Appointments");

        scrollPanel.setBackground(new java.awt.Color(248, 249, 254));
        scrollPanel.setBorder(null);
        scrollPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPanel.setOpaque(false);
        scrollPanel.setViewportView(appointmentsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lblHeader))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1029, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private src.frames.tabs.DashboardComponents.appointmentsPanel appointmentsPanel;
    private src.frames.components.background headerPanel;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblName;
    private javax.swing.JScrollPane scrollPanel;
    // End of variables declaration//GEN-END:variables
}
