/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src.frames;
import java.util.ArrayList;
import src.models.*;
import src.util.*;
import src.frames.tabs.Admin;
import src.frames.tabs.Dashboard;
/**
 *
 * Alert Frame
 */
public class Alert extends Frame {

    /**
     * admin tab
     */
    private Admin admin;

    /**
     * dashboard tab
     */
    private Dashboard dashboard;

    /**
     * the user
     */
    private user user;

    /**
     * the appointment
     */
    private appointment appointment;
    /**
     * Constructor to create delete Appointment Alert
     * @param dashboard
     * @param appointment
     * @param user
     */
    public Alert(Dashboard dashboard, appointment appointment, user user) {
        this.dashboard = dashboard;
        this.appointment = appointment;
        this.user = user;
        init();
        lblText.setText("Do you really want to delete your Appointment ?");
        lblError.setText("Error i cant delete your Appointment");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDeleteMousePressedAppointment(evt);
            }
        });
    }
    
    /**
     * Constructor to create delete User Alert
     * @param admin
     * @param user
     */
    public Alert(Admin admin,user user) {
        this.admin = admin;
        this.user = user;
        init();
        lblText.setText("Do you really want to delete this Account ?");
        lblError.setText("Error i cant delete this Account");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDeleteMousePressedUser(evt);
            }
        });
    }
    
    /**
     * init components
     * we cant init the values in the constructor because the netbeans gui builder doesent allow custom parameters
     */
    private void init(){
        initComponents();
        winButton.init(this, background,false);
        dragPanel.init(this, background);
        lblError.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new src.frames.components.background();
        winButton = new src.frames.components.headButton.WinButton();
        dragPanel = new src.frames.components.dragPanel();
        lblText = new javax.swing.JLabel();
        btnDelete = new src.frames.components.button();
        btnCancel = new src.frames.components.button();
        lblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(248, 249, 254));

        javax.swing.GroupLayout dragPanelLayout = new javax.swing.GroupLayout(dragPanel);
        dragPanel.setLayout(dragPanelLayout);
        dragPanelLayout.setHorizontalGroup(
            dragPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 239, Short.MAX_VALUE)
        );
        dragPanelLayout.setVerticalGroup(
            dragPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        lblText.setBackground(new java.awt.Color(255, 255, 255));
        lblText.setFont(fnt(12f)
        );
        lblText.setText("Do you really want to delete this Account?");

        btnDelete.setBackground(new java.awt.Color(205, 61, 100));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.setFont(fnt(15f));

        btnCancel.setBackground(new java.awt.Color(204, 204, 204));
        btnCancel.setText("Cancel");
        btnCancel.setFont(fnt(15f));
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCancelMousePressed(evt);
            }
        });

        lblError.setFont(fnt(14f));
        lblError.setForeground(new java.awt.Color(205, 61, 100));
        lblError.setText("Cant delete this Account");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(dragPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(winButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblText)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(lblError)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dragPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(winButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(lblText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(lblError)
                .addGap(32, 32, 32)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Cancel Action
     * @param evt 
     */
    private void btnCancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMousePressed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCancelMousePressed

    /**
     * Delete Appointment
     * @param evt
     */
    private void btnDeleteMousePressedAppointment(java.awt.event.MouseEvent evt) { 
        lblError.setVisible(false);
        if(!database.deleteAppointment(appointment)){
            lblError.setVisible(true);
            return;
        }
        mail.appointmentCancel(appointment, user);
        setVisible(false);
        dispose();
        user.removeAppointment(appointment);
        dashboard.init(user);
    }
    
    /**
     * Delete User
     * @param evt
     */
    private void btnDeleteMousePressedUser(java.awt.event.MouseEvent evt) { 
        lblError.setVisible(false);
        if(!database.deleteUser(user)){
            lblError.setVisible(true);
            return;
        }
        setVisible(false);
        dispose();
        admin.init(admin.loginUser);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private src.frames.components.background background;
    private src.frames.components.button btnCancel;
    private src.frames.components.button btnDelete;
    private src.frames.components.dragPanel dragPanel;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblText;
    private src.frames.components.headButton.WinButton winButton;
    // End of variables declaration//GEN-END:variables
}
