/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src.frames;

import java.awt.CardLayout;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import src.models.user;
import src.util.*;

/**
 *
 * Register Frame
 */
public class Register extends Frame {

    /**
     * the cardlayout of the mainPanel
     */
    CardLayout card;

    /**
     * the new user
     */
    user newUser = new user();
    /**
     * Constructor to create a new Register Frame
     */
    public Register() {
        setPreferredSize(new java.awt.Dimension(839, 519));
        initComponents();
        winButton.init(this, background,false);
        dragPanel.init(this, background);
        lblErrorUserPanel.setVisible(false);
        lblErrorHealthPanel.setVisible(false);
        lblErroraccessDataPanel.setVisible(false);
        card = (CardLayout)mainPanel.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupGender = new javax.swing.ButtonGroup();
        groupInsuranceType = new javax.swing.ButtonGroup();
        background = new src.frames.components.background();
        winButton = new src.frames.components.headButton.WinButton();
        dragPanel = new src.frames.components.dragPanel();
        jLabel1 = new javax.swing.JLabel();
        lblRegister = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        userPanel = new javax.swing.JPanel();
        btnCancel = new src.frames.components.button();
        btnNextUserPanel = new src.frames.components.button();
        lblFirstname = new javax.swing.JLabel();
        lblLastname = new javax.swing.JLabel();
        txtFirstname = new src.frames.components.textfield();
        sepFirstname = new javax.swing.JSeparator();
        txtLastname = new src.frames.components.textfield();
        sepLastname = new javax.swing.JSeparator();
        lblStreet = new javax.swing.JLabel();
        lblHousenumber = new javax.swing.JLabel();
        lblZipcode = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        txtStreet = new src.frames.components.textfield();
        sepStreet = new javax.swing.JSeparator();
        txtHousenumber = new src.frames.components.textfield();
        sepHousenumber = new javax.swing.JSeparator();
        txtZipcode = new src.frames.components.textfield();
        sepZipcode = new javax.swing.JSeparator();
        txtCity = new src.frames.components.textfield();
        sepCity = new javax.swing.JSeparator();
        lblGender = new javax.swing.JLabel();
        jRadioMale = new javax.swing.JRadioButton();
        jRadioFemale = new javax.swing.JRadioButton();
        jRadioDiverse = new javax.swing.JRadioButton();
        lblDateOfBirth = new javax.swing.JLabel();
        txtDateOfBirth = new src.frames.components.textfield();
        sepDateOfBirth = new javax.swing.JSeparator();
        lblErrorUserPanel = new javax.swing.JLabel();
        healthPanel = new javax.swing.JPanel();
        btnBackHealthPanel = new src.frames.components.button();
        btnNextHealthPanel = new src.frames.components.button();
        lblInsurancename = new javax.swing.JLabel();
        txtInsurancename = new src.frames.components.textfield();
        sepInsurancename = new javax.swing.JSeparator();
        lblInsurancetype = new javax.swing.JLabel();
        jRadioPublic = new javax.swing.JRadioButton();
        jRadioPrivate = new javax.swing.JRadioButton();
        lblHealthInformation = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHealthInformation = new javax.swing.JTextArea();
        lblErrorHealthPanel = new javax.swing.JLabel();
        accessDataPanel = new javax.swing.JPanel();
        btnBackaccessDataPanel = new src.frames.components.button();
        btnRegister = new src.frames.components.button();
        sepEmail = new javax.swing.JSeparator();
        sepPasswordConfirm = new javax.swing.JSeparator();
        lblEmail = new javax.swing.JLabel();
        txtPasswordConfirm = new src.frames.components.passwordfield();
        lblPasswordConfirm = new javax.swing.JLabel();
        txtEmail = new src.frames.components.textfield();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new src.frames.components.textfield();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new src.frames.components.passwordfield();
        sepPassword = new javax.swing.JSeparator();
        sepUsername = new javax.swing.JSeparator();
        lblErroraccessDataPanel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout dragPanelLayout = new javax.swing.GroupLayout(dragPanel);
        dragPanel.setLayout(dragPanelLayout);
        dragPanelLayout.setHorizontalGroup(
            dragPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        dragPanelLayout.setVerticalGroup(
            dragPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/loginsidepanel.png"))); // NOI18N

        lblRegister.setFont(fnt(22f));
        lblRegister.setText("Register");

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        userPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnCancel.setBackground(new java.awt.Color(204, 204, 204));
        btnCancel.setText("Cancel");
        btnCancel.setFont(fnt(15f));
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCancelMousePressed(evt);
            }
        });

        btnNextUserPanel.setBackground(new java.awt.Color(69, 125, 88));
        btnNextUserPanel.setForeground(new java.awt.Color(255, 255, 255));
        btnNextUserPanel.setText("Next");
        btnNextUserPanel.setFont(fnt(15f));
        btnNextUserPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextUserPanelActionPerformed(evt);
            }
        });

        lblFirstname.setFont(fnt(16f));
        lblFirstname.setText("Firstname");

        lblLastname.setFont(fnt(16f));
        lblLastname.setText("Lastname");

        txtFirstname.setForeground(Frame.textInput);
        txtFirstname.setText("Enter Firstname");
        txtFirstname.setFont(fnt(14f));

        sepFirstname.setForeground(Frame.textInput);

        txtLastname.setForeground(Frame.textInput);
        txtLastname.setText("Enter Lastname");
        txtLastname.setFont(fnt(14f));

        sepLastname.setForeground(Frame.textInput);

        lblStreet.setFont(fnt(16f));
        lblStreet.setText("Street");

        lblHousenumber.setFont(fnt(16f));
        lblHousenumber.setText("Housenumber");

        lblZipcode.setFont(fnt(16f));
        lblZipcode.setText("Zipcode");

        lblCity.setFont(fnt(16f));
        lblCity.setText("City");

        txtStreet.setForeground(Frame.textInput);
        txtStreet.setText("Enter Street");
        txtStreet.setFont(fnt(14f));

        sepStreet.setForeground(Frame.textInput);

        txtHousenumber.setForeground(Frame.textInput);
        txtHousenumber.setText("123");
        txtHousenumber.setFont(fnt(14f));

        sepHousenumber.setForeground(Frame.textInput);

        txtZipcode.setForeground(Frame.textInput);
        txtZipcode.setText("12345");
        txtZipcode.setFont(fnt(14f));

        sepZipcode.setForeground(Frame.textInput);

        txtCity.setForeground(Frame.textInput);
        txtCity.setText("Enter City");
        txtCity.setFont(fnt(14f));

        sepCity.setForeground(Frame.textInput);

        lblGender.setFont(fnt(16f));
        lblGender.setText("Gender");

        groupGender.add(jRadioMale);
        jRadioMale.setFont(fnt(16f));
        jRadioMale.setText("male");
        jRadioMale.setOpaque(false);

        groupGender.add(jRadioFemale);
        jRadioFemale.setFont(fnt(16f));
        jRadioFemale.setText("female");
        jRadioFemale.setOpaque(false);

        groupGender.add(jRadioDiverse);
        jRadioDiverse.setFont(fnt(16f));
        jRadioDiverse.setText("diverse");
        jRadioDiverse.setOpaque(false);

        lblDateOfBirth.setFont(fnt(16f));
        lblDateOfBirth.setText("Date of Birth");

        txtDateOfBirth.setForeground(Frame.textInput);
        txtDateOfBirth.setText("01.01.1990");
        txtDateOfBirth.setFont(fnt(14f));

        sepDateOfBirth.setForeground(Frame.textInput);

        lblErrorUserPanel.setFont(fnt(16f));
        lblErrorUserPanel.setForeground(new java.awt.Color(205, 61, 100));
        lblErrorUserPanel.setText("Missing Values");

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNextUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addComponent(lblErrorUserPanel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addComponent(lblGender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioMale)
                        .addGap(34, 34, 34)
                        .addComponent(jRadioFemale)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioDiverse))
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(sepFirstname, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtFirstname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                            .addComponent(lblFirstname))
                        .addGap(13, 13, 13)
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(userPanelLayout.createSequentialGroup()
                                .addComponent(lblLastname)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtLastname, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(sepLastname)))
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblStreet, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStreet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                            .addComponent(sepStreet, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, userPanelLayout.createSequentialGroup()
                                .addComponent(lblZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCity)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(userPanelLayout.createSequentialGroup()
                                .addComponent(lblHousenumber)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtHousenumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sepHousenumber)))
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(sepZipcode, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtZipcode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sepCity)))
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addComponent(lblDateOfBirth)
                        .addGap(123, 123, 123)
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sepDateOfBirth)
                            .addComponent(txtDateOfBirth, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))))
                .addContainerGap())
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstname)
                    .addComponent(lblLastname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sepFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sepLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStreet)
                            .addComponent(lblHousenumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHousenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addComponent(sepStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sepHousenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZipcode)
                    .addComponent(lblCity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sepZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sepCity, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGender)
                    .addComponent(jRadioFemale)
                    .addComponent(jRadioMale)
                    .addComponent(jRadioDiverse))
                .addGap(34, 34, 34)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateOfBirth)
                    .addComponent(txtDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sepDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(lblErrorUserPanel)
                .addGap(27, 27, 27)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNextUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        mainPanel.add(userPanel, "card2");

        healthPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnBackHealthPanel.setBackground(new java.awt.Color(204, 204, 204));
        btnBackHealthPanel.setText("Back");
        btnBackHealthPanel.setFont(fnt(15f));
        btnBackHealthPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBackHealthPanelMousePressed(evt);
            }
        });

        btnNextHealthPanel.setBackground(new java.awt.Color(69, 125, 88));
        btnNextHealthPanel.setForeground(new java.awt.Color(255, 255, 255));
        btnNextHealthPanel.setText("Next");
        btnNextHealthPanel.setFont(fnt(15f));
        btnNextHealthPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNextHealthPanelMousePressed(evt);
            }
        });

        lblInsurancename.setFont(fnt(16f));
        lblInsurancename.setText("Insurancename");

        txtInsurancename.setForeground(Frame.textInput);
        txtInsurancename.setText("Enter Insurancename");
        txtInsurancename.setFont(fnt(14f));

        sepInsurancename.setForeground(Frame.textInput);

        lblInsurancetype.setFont(fnt(16f));
        lblInsurancetype.setText("Insurancetype");

        groupInsuranceType.add(jRadioPublic);
        jRadioPublic.setFont(fnt(16f));
        jRadioPublic.setText("public");
        jRadioPublic.setOpaque(false);
        jRadioPublic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRadioPublicMousePressed(evt);
            }
        });

        groupInsuranceType.add(jRadioPrivate);
        jRadioPrivate.setFont(fnt(16f));
        jRadioPrivate.setText("private");
        jRadioPrivate.setOpaque(false);
        jRadioPrivate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRadioPrivateMousePressed(evt);
            }
        });

        lblHealthInformation.setFont(fnt(16f));
        lblHealthInformation.setText("Health Information");

        txtHealthInformation.setColumns(20);
        txtHealthInformation.setFont(fnt(14f));
        txtHealthInformation.setForeground(Frame.textInput);
        txtHealthInformation.setRows(5);
        jScrollPane1.setViewportView(txtHealthInformation);

        lblErrorHealthPanel.setFont(fnt(16f));
        lblErrorHealthPanel.setForeground(new java.awt.Color(205, 61, 100));
        lblErrorHealthPanel.setText("Missing Values");

        javax.swing.GroupLayout healthPanelLayout = new javax.swing.GroupLayout(healthPanel);
        healthPanel.setLayout(healthPanelLayout);
        healthPanelLayout.setHorizontalGroup(
            healthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(healthPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(healthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(healthPanelLayout.createSequentialGroup()
                        .addComponent(btnBackHealthPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNextHealthPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(healthPanelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(healthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, healthPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addContainerGap())
                            .addGroup(healthPanelLayout.createSequentialGroup()
                                .addComponent(lblInsurancename)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(healthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sepInsurancename)
                                    .addComponent(txtInsurancename, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                                .addContainerGap())
                            .addGroup(healthPanelLayout.createSequentialGroup()
                                .addComponent(lblInsurancetype)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                                .addComponent(jRadioPublic)
                                .addGap(34, 34, 34)
                                .addComponent(jRadioPrivate)
                                .addGap(39, 39, 39))
                            .addGroup(healthPanelLayout.createSequentialGroup()
                                .addGroup(healthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblErrorHealthPanel)
                                    .addComponent(lblHealthInformation))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        healthPanelLayout.setVerticalGroup(
            healthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, healthPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(healthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInsurancename)
                    .addComponent(txtInsurancename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sepInsurancename, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(healthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInsurancetype)
                    .addComponent(jRadioPrivate)
                    .addComponent(jRadioPublic))
                .addGap(32, 32, 32)
                .addComponent(lblHealthInformation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(lblErrorHealthPanel)
                .addGap(26, 26, 26)
                .addGroup(healthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBackHealthPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNextHealthPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        mainPanel.add(healthPanel, "card3");

        accessDataPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnBackaccessDataPanel.setBackground(new java.awt.Color(204, 204, 204));
        btnBackaccessDataPanel.setText("Back");
        btnBackaccessDataPanel.setFont(fnt(15f));
        btnBackaccessDataPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBackaccessDataPanelMousePressed(evt);
            }
        });

        btnRegister.setBackground(new java.awt.Color(69, 125, 88));
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Register");
        btnRegister.setFont(fnt(15f));
        btnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRegisterMousePressed(evt);
            }
        });

        sepEmail.setForeground(Frame.textInput);

        sepPasswordConfirm.setForeground(Frame.textInput);

        lblEmail.setFont(fnt(16f));
        lblEmail.setText("Email");

        txtPasswordConfirm.setForeground(Frame.textInput);
        txtPasswordConfirm.setText("Enter Password again");
        txtPasswordConfirm.setFont(fnt(14f));

        lblPasswordConfirm.setFont(fnt(16f));
        lblPasswordConfirm.setText("Confirm Password");

        txtEmail.setForeground(Frame.textInput);
        txtEmail.setText("Enter Email");
        txtEmail.setFont(fnt(14f));

        lblUsername.setFont(fnt(16f));
        lblUsername.setText("Username");

        txtUsername.setForeground(Frame.textInput);
        txtUsername.setText("Enter Username");
        txtUsername.setFont(fnt(14f));

        lblPassword.setFont(fnt(16f));
        lblPassword.setText("Password");

        txtPassword.setForeground(Frame.textInput);
        txtPassword.setFont(fnt(14f));

        sepPassword.setForeground(Frame.textInput);

        sepUsername.setForeground(Frame.textInput);

        lblErroraccessDataPanel.setFont(fnt(16f));
        lblErroraccessDataPanel.setForeground(new java.awt.Color(205, 61, 100));
        lblErroraccessDataPanel.setText("Missing Values");

        javax.swing.GroupLayout accessDataPanelLayout = new javax.swing.GroupLayout(accessDataPanel);
        accessDataPanel.setLayout(accessDataPanelLayout);
        accessDataPanelLayout.setHorizontalGroup(
            accessDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accessDataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBackaccessDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(accessDataPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(accessDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accessDataPanelLayout.createSequentialGroup()
                        .addComponent(lblErroraccessDataPanel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(accessDataPanelLayout.createSequentialGroup()
                        .addGroup(accessDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(accessDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblUsername)
                                .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sepUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(accessDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblPassword)
                                .addComponent(sepPassword)
                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addGroup(accessDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(accessDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblEmail)
                                .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sepEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(accessDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblPasswordConfirm)
                                .addComponent(txtPasswordConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sepPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        accessDataPanelLayout.setVerticalGroup(
            accessDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accessDataPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(accessDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, accessDataPanelLayout.createSequentialGroup()
                        .addComponent(lblUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sepUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPassword)
                        .addGap(11, 11, 11)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sepPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(accessDataPanelLayout.createSequentialGroup()
                        .addComponent(lblEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sepEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(accessDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(accessDataPanelLayout.createSequentialGroup()
                                .addGroup(accessDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(accessDataPanelLayout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(txtPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblPasswordConfirm))
                                .addGap(23, 23, 23))
                            .addComponent(sepPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(46, 46, 46)
                .addComponent(lblErroraccessDataPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addGroup(accessDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBackaccessDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        mainPanel.add(accessDataPanel, "card4");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(dragPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(winButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(lblRegister)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(winButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(dragPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(lblRegister)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Go back to Login Frame
     * @param evt 
     */
    private void btnCancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMousePressed
        setVisible(false);
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCancelMousePressed
    /**
     * Switch to the next Tab of the mainPanel
     * @param evt 
     */
    private void btnNextUserPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextUserPanelActionPerformed
        lblErrorUserPanel.setVisible(false);
        if(txtFirstname.getText().length() == 0 || !txtFirstname.getReset()){
            lblErrorUserPanel.setText("Firstname is missing");
            lblErrorUserPanel.setVisible(true);
            return;
        }
        
        if(txtLastname.getText().length() == 0 || !txtLastname.getReset()){
            lblErrorUserPanel.setText("Lastname is missing");
            lblErrorUserPanel.setVisible(true);
            return;
        }
        
        if(txtStreet.getText().length() == 0 || !txtStreet.getReset()){
            lblErrorUserPanel.setText("Street is missing");
            lblErrorUserPanel.setVisible(true);
            return;
        }
        
        if(txtHousenumber.getText().length() == 0 || !txtHousenumber.getReset()){
            lblErrorUserPanel.setText("Housenumber is missing");
            lblErrorUserPanel.setVisible(true);
            return;
        }
        
        if(txtZipcode.getText().length() == 0 || !txtZipcode.getReset()){
            lblErrorUserPanel.setText("Zipcode is missing");
            lblErrorUserPanel.setVisible(true);
            return;
        }
        
        if(txtCity.getText().length() == 0 || !txtCity.getReset()){
            lblErrorUserPanel.setText("City is missing");
            lblErrorUserPanel.setVisible(true);
            return;
        }
        
        if(!jRadioMale.isSelected() && !jRadioFemale.isSelected() && !jRadioDiverse.isSelected()){
            lblErrorUserPanel.setText("Gender is missing");
            lblErrorUserPanel.setVisible(true);
            return;
        }
        
        if(txtDateOfBirth.getText().length() == 0 || !txtDateOfBirth.getReset()){
            lblErrorUserPanel.setText("Date of Birth is missing");
            lblErrorUserPanel.setVisible(true);
            return;
        }
        
        try{
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("d.MM.yyyy");
            newUser.setDateofbirth(LocalDate.parse(txtDateOfBirth.getText(), formatter));
        }catch(Exception ex){
            lblErrorUserPanel.setText("Date of Birth is in the Wrong Format (dd.mm.yyyy)");
            lblErrorUserPanel.setVisible(true);
            return;
        }
        
        newUser.setFirstname(txtFirstname.getText());
        newUser.setLastname(txtLastname.getText());
        newUser.setStreet(txtStreet.getText());
        newUser.setHousenumber(txtHousenumber.getText());
        newUser.setZipcode(txtZipcode.getText());
        newUser.setCity(txtCity.getText());
        
        if(jRadioMale.isSelected()){
            newUser.setGender("m");
        }else if(jRadioFemale.isSelected()){
            newUser.setGender("f");
        }else{
            newUser.setGender("d");
        }
        
        if(!googlemaps.getLatLong(newUser)){
            lblErrorUserPanel.setText("Address dosent exist");
            lblErrorUserPanel.setVisible(true);
            return;
        }
        
        card.next(mainPanel);
    }//GEN-LAST:event_btnNextUserPanelActionPerformed
    /**
     * Go back to the previous Tab of the mainPanel
     * @param evt 
     */
    private void btnBackHealthPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackHealthPanelMousePressed
        card.previous(mainPanel);
    }//GEN-LAST:event_btnBackHealthPanelMousePressed
    /**
     * Switch to the next Tab of the mainPanel
     * @param evt 
     */
    private void btnNextHealthPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextHealthPanelMousePressed
        lblErrorHealthPanel.setVisible(false);
        
        if(!jRadioPublic.isSelected() && !jRadioPrivate.isSelected()){
            lblErrorHealthPanel.setText("Insurancetype is missing");
            lblErrorHealthPanel.setVisible(true);
            return;
        }
        
        newUser.setInsurancename(txtInsurancename.getText());
        if(jRadioPublic.isSelected()){
            if(txtInsurancename.getText().length() == 0 || !txtInsurancename.getReset()){
                lblErrorHealthPanel.setText("Insurancename is missing");
                lblErrorHealthPanel.setVisible(true);
                return;
            }
            newUser.setInsurancetype("public");
        }else{
            newUser.setInsurancetype("private");
        }
        
        newUser.setHealthinformation(txtHealthInformation.getText());
        
        card.next(mainPanel);
    }//GEN-LAST:event_btnNextHealthPanelMousePressed
    /**
     * Go back to the previous Tab of the mainPanel
     * @param evt 
     */
    private void btnBackaccessDataPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackaccessDataPanelMousePressed
        card.previous(mainPanel);
    }//GEN-LAST:event_btnBackaccessDataPanelMousePressed
    /**
     * Register new User
     * @param evt 
     */
    private void btnRegisterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMousePressed
        lblErroraccessDataPanel.setVisible(false);
        if(txtUsername.getText().length() == 0 || !txtUsername.getReset()){
            lblErroraccessDataPanel.setText("Username is missing");
            lblErroraccessDataPanel.setVisible(true);
            return;
        }
        
        if(txtEmail.getText().length() == 0 || !txtEmail.getReset()){
            lblErroraccessDataPanel.setText("Email is missing");
            lblErroraccessDataPanel.setVisible(true);
            return;
        }
        
        if(txtPassword.getPassword().length == 0 || !txtPassword.getReset()){
            lblErroraccessDataPanel.setText("Password is missing");
            lblErroraccessDataPanel.setVisible(true);
            return;
        }
        
        if(txtPasswordConfirm.getPassword().length == 0 || !txtPasswordConfirm.getReset()){
            lblErroraccessDataPanel.setText("Password Confirm is missing");
            lblErroraccessDataPanel.setVisible(true);
            return;
        }
        
        if(!new String(txtPassword.getPassword()).equals(new String(txtPasswordConfirm.getPassword()))){
            lblErroraccessDataPanel.setText("The Passwords are not equal");
            lblErroraccessDataPanel.setVisible(true);
            return;
        }
        btnRegister.setEnabled(false);
        btnRegister.setText("Register ....");
        
        if(!database.checkAvailable(txtUsername.getText(), txtEmail.getText())){
            btnRegister.setText("Register");
            btnRegister.setEnabled(true);
            lblErroraccessDataPanel.setText("Username or Email are not available");
            lblErroraccessDataPanel.setVisible(true);
            return;
        }
        newUser.setUsername(txtUsername.getText());
        newUser.setEmail(txtEmail.getText());
        newUser.setPassword(password.getHash(new String(txtPassword.getPassword())));
        
        newUser = database.createUser(newUser);
        if(newUser == null){
            btnRegister.setText("Register");
            btnRegister.setEnabled(true);
            lblErroraccessDataPanel.setText("Cant create new User");
            lblErroraccessDataPanel.setVisible(true);
            return;
        }
        
        setVisible(false);
        new Home(newUser).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegisterMousePressed
    /**
     * Disable txtInsurancename if private is selected
     * @param evt 
     */
    private void jRadioPrivateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioPrivateMousePressed
        txtInsurancename.setEnabled(false);
        txtInsurancename.setText("");
    }//GEN-LAST:event_jRadioPrivateMousePressed
    /**
     * Enable txtInsurancename if public is selected
     * @param evt 
     */
    private void jRadioPublicMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioPublicMousePressed
        txtInsurancename.setEnabled(true);
    }//GEN-LAST:event_jRadioPublicMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accessDataPanel;
    private src.frames.components.background background;
    private src.frames.components.button btnBackHealthPanel;
    private src.frames.components.button btnBackaccessDataPanel;
    private src.frames.components.button btnCancel;
    private src.frames.components.button btnNextHealthPanel;
    private src.frames.components.button btnNextUserPanel;
    private src.frames.components.button btnRegister;
    private src.frames.components.dragPanel dragPanel;
    private javax.swing.ButtonGroup groupGender;
    private javax.swing.ButtonGroup groupInsuranceType;
    private javax.swing.JPanel healthPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioDiverse;
    private javax.swing.JRadioButton jRadioFemale;
    private javax.swing.JRadioButton jRadioMale;
    private javax.swing.JRadioButton jRadioPrivate;
    private javax.swing.JRadioButton jRadioPublic;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblDateOfBirth;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblErrorHealthPanel;
    private javax.swing.JLabel lblErrorUserPanel;
    private javax.swing.JLabel lblErroraccessDataPanel;
    private javax.swing.JLabel lblFirstname;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHealthInformation;
    private javax.swing.JLabel lblHousenumber;
    private javax.swing.JLabel lblInsurancename;
    private javax.swing.JLabel lblInsurancetype;
    private javax.swing.JLabel lblLastname;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordConfirm;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JLabel lblStreet;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblZipcode;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JSeparator sepCity;
    private javax.swing.JSeparator sepDateOfBirth;
    private javax.swing.JSeparator sepEmail;
    private javax.swing.JSeparator sepFirstname;
    private javax.swing.JSeparator sepHousenumber;
    private javax.swing.JSeparator sepInsurancename;
    private javax.swing.JSeparator sepLastname;
    private javax.swing.JSeparator sepPassword;
    private javax.swing.JSeparator sepPasswordConfirm;
    private javax.swing.JSeparator sepStreet;
    private javax.swing.JSeparator sepUsername;
    private javax.swing.JSeparator sepZipcode;
    private src.frames.components.textfield txtCity;
    private src.frames.components.textfield txtDateOfBirth;
    private src.frames.components.textfield txtEmail;
    private src.frames.components.textfield txtFirstname;
    private javax.swing.JTextArea txtHealthInformation;
    private src.frames.components.textfield txtHousenumber;
    private src.frames.components.textfield txtInsurancename;
    private src.frames.components.textfield txtLastname;
    private src.frames.components.passwordfield txtPassword;
    private src.frames.components.passwordfield txtPasswordConfirm;
    private src.frames.components.textfield txtStreet;
    private src.frames.components.textfield txtUsername;
    private src.frames.components.textfield txtZipcode;
    private javax.swing.JPanel userPanel;
    private src.frames.components.headButton.WinButton winButton;
    // End of variables declaration//GEN-END:variables
}
