/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package src.frames.components;

import javax.swing.JFrame;

/**
 *
 * Custom dragPanel 
 * We need that because the Program is Undecorated
 */
public class dragPanel extends javax.swing.JPanel {

    /**
     * Frame that contains the dragPanel
     */
    
    private JFrame frame;

    /**
     * background of the sidepanel to calculate the coordinates correctly
     */
    private background background;

    /**
     * x coordinate of the position where the user clicked at
     */
    private int xPress;

    /**
     * y coordinate of the position where the user clicked at
     */
    private int yPress;

    /**
     * the width of the sidepanel set in the constructor,0 if the frame is the login or register
     */
    private int xPressMinus = 0;
    
    /**
     * Constructor to create drapPanel
     */
    public dragPanel() {
        initComponents();
    }
    
    /**
     * init the frame and background used by the login and register frame
     * we cant init the values in the constructor because the netbeans gui builder doesent allow custom parameters
     * @param frame
     * @param background
     */
    public void init(JFrame frame, background background){
        this.frame = frame;
        this.background = background;
    }
    
    /**
     * init the frame, background and width of the sidebar used by the home frame
     * we cant init the values in the constructor because the netbeans gui builder doesent allow custom parameters
     * @param frame
     * @param background
     * @param width
     */
    public void init(JFrame frame, background background,int width){
        this.frame = frame;
        this.background = background;
        this.xPressMinus = width;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setOpaque(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 789, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Actionlistener Mouse Drag 
     * Move the window to the coordinates
     * @param evt 
     */
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        frame.setLocation(x - xPress-xPressMinus, y - yPress);
    }//GEN-LAST:event_formMouseDragged
    /**
     * Actionlistener Mousepress 
     * Update the users x and y coordinates
     * @param evt 
     */
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
         if (frame.getExtendedState() == JFrame.MAXIMIZED_BOTH) {
            background.setRound(20);
            frame.setExtendedState(JFrame.NORMAL);
        } 
        xPress = evt.getX();
        yPress = evt.getY();
    }//GEN-LAST:event_formMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
